### ISSUE TITLE
error with installing Asterisk

### ISSUE THREAD

**Issue by drtechga** [Allan-N/ASL-Install#7]
Hello i ran your script on a Linode debain12 instance, and asterisk seems to be not installed. Under diag menu option 3 and 4 say unable to connect to remote asterisk (does /var/run/asterisk.ctl exist?

Any help?

Thanks
KK4JMW

**Comment by Allan-N** [comment]
Well, I have questions for you and hopefully one of them will point to the answer.

Did you run into any issues when running the `asl-install.sh` script, especially steps 1-6 ?  Here, I will add that the script saves some log files of the build and install in the `/var/tmp` directory.  You might want to look for errors in `/var/tmp/build-dahdi.txt`, `/var/tmp/build-asterisk.txt`, etc.

The downloaded `ASL-Install` directory includes a script that will check to see what services have been enabled/running.  To exec the script you would :
```
cd <ASL-Install directory>
sudo ./check-asl-services
```

You mention "diag menu option 3 and 4".  What command(s) and steps are you using to get to this "diag menu"?

**Comment by Allan-N** [comment]
Also, were you running whatever command you were using to look at the diags as the "root" user (or with `sudo`) ?

**Comment by hwdornbush** [comment]
I am also having trouble getting Asterisk to run.  My environment is Pi 4 with Bookworm downloaded and nothing else done in it before downloading and running asl-install.sh.  Is saw no error messages when running the script.  Here is the output from check-asl-services.sh:

● dahdi.service - LSB: DAHDI kernel modules
     Loaded: loaded (/etc/init.d/dahdi; generated)
     Active: active (exited) since Sun 2024-02-18 14:27:00 EST; 26min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 1176 ExecStart=/etc/init.d/dahdi start (code=exited, status=0/SUCCESS)
        CPU: 27ms

Feb 18 14:27:00 localhost.localdomain systemd[1]: Starting dahdi.service - LSB: DAHDI kernel modules...
Feb 18 14:27:00 localhost.localdomain dahdi[1176]: No DAHDI modules on the system. Not starting
Feb 18 14:27:00 localhost.localdomain systemd[1]: Started dahdi.service - LSB: DAHDI kernel modules.
○ asterisk.service - Asterisk PBX and telephony daemon
     Loaded: loaded (/lib/systemd/system/asterisk.service; enabled; preset: enabled)
     Active: inactive (dead)
       Docs: man:asterisk(8)

Feb 18 14:28:34 localhost.localdomain systemd[1]: Dependency failed for asterisk.service - Asterisk PBX and telephony d>
Feb 18 14:28:34 localhost.localdomain systemd[1]: asterisk.service: Job asterisk.service/start failed with result 'depe>
lines 1-7/7 (END)

I don't really know what to look for in the log files.  In looking at /var/tmp/build-asterisk.  There were lots of yes and no.  The only thing that jumped out at me was:

checking for pkg-config... pkg-config
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-2.0', required by 'virtual:world', not found
configure: creating ./config.status
config.status: creating makeopts
config.status: creating autoconfig.h
configure: configuring in mxml
configure: running /bin/bash './configure' --prefix=/usr/local  --cache-file=/dev/null --srcdir=.

Since I am new at both ASL and Linux, I am not sure where to go from here.

**Comment by Allan-N** [comment]
@hwdornbush It really helps me (and others) to keep issues reported by one person separate from those of another.  This issue was reported for an "Linode debian 12" [Virtual Machine] instance.  You are having issues on a Raspberry Pi. 

Please feel free to create a new issue for any followup on your installation / issues.

**Comment by Allan-N** [comment]
@drtechga Did you make any progress on your Linode ASL install?  If all is well or you've moved on then I'd like to close this issue.

**Comment by Allan-N** [comment]
No response
